from django.db import models
from django.contrib.auth.models import User

import zipfile

class DataPackage(models.Model):
    user = models.ForeignKey(User, null=True, editable=False, on_delete=models.SET_NULL) 
    package = models.FileField(upload_to='{}'.format('datapackages')) 
    packageDate=models.DateTimeField(auto_now=True)
    notes = models.TextField(max_length=500)
    
class Molecule(models.Model):
    smiles = models.TextField()
    inchiKey = models.TextField(max_length=27)
    parentMolecule = models.ForeignKey('self', null=True, editable=False, on_delete=models.SET_NULL)
    
class Solubility(models.Model):
    molecule = models.ForeignKey(Molecule, null=True, editable=False, on_delete=models.SET_NULL)
    solubilityAqSolPred = models.DecimalField(blank=True, null=True, max_digits=50, decimal_places=5)
    
class FunctionalGroup(models.Model):
    stoichiometry = models.TextField(max_length=20, blank=True, null=True, default=None)

class JobSetting(models.Model):
    basisSet = models.TextField(max_length=16, default=None)
    netMoleculerCharge = models.IntegerField(default=None)
    multiplicity = models.IntegerField(default=None)
    solvent = models.TextField(max_length=16, blank=True, null=True, default=None)
    scfCalculation = models.TextField(max_length=16, blank=True, null=True, default=None)
    dft = models.TextField(max_length=50, blank=True, null=True, default=None)
    solvationEnergy = models.TextField(max_length=16, blank=True, null=True, default=None)
    hyperPolEqu = models.TextField(max_length=50, blank=True, null=True, default=None)
    maxScfIterations = models.PositiveSmallIntegerField(default=None)
    internalDielectric = models.TextField(max_length=16, blank=True, null=True, default=None)
    continuumDielectric = models.TextField(max_length=16, blank=True, null=True, default=None)
    solventProbe = models.TextField(max_length=16, blank=True, null=True, default=None)
    pbfVersion = models.TextField(max_length=16, blank=True, null=True, default=None)
     
class MoleculeInfo(models.Model):
    moleculerWeight = models.DecimalField(blank=True, null=True, max_digits=50, decimal_places=5)
    stoichiometry = models.TextField(max_length=50)
    
class Job(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    jobType = models.TextField(max_length=15, blank=True, null=True, default=None)
    calcNumber = models.PositiveSmallIntegerField(default=None)
    jobSetting = models.ForeignKey(JobSetting, on_delete=models.CASCADE, default=None)
    moleculeInfo = models.ForeignKey(MoleculeInfo, on_delete=models.CASCADE, default=None)
    functionalGroup = models.ForeignKey(FunctionalGroup, null=True, editable=False, on_delete=models.SET_NULL)
    jobId = models.TextField(max_length=15, blank=True, null=True, default=None)
    name = models.TextField(max_length=16, blank=True, null=True, default=None)
    path = models.TextField(max_length=500, blank=True, null=True, default=None)
    dataPackage = models.ForeignKey(DataPackage, null=True, editable=False, on_delete=models.SET_NULL)
    molecule = models.ForeignKey(Molecule, null=True, editable=False, on_delete=models.SET_NULL)
    reactionStep = models.PositiveSmallIntegerField(default=None)
       
class PbfCalc(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, default=None)
    molecularSurface = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    reactionFieldEnergy = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    solventAccessSurface = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    cavityEnergy = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    
class OtherInfo(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, default=None)
    nuclearRepulsionEnergy = models.DecimalField(blank=True, null=True, max_digits=30, decimal_places=15)
    pointGroupUsed = models.TextField(max_length=5, blank=True, null=True, default=None)
    molecularPointGroup = models.TextField(max_length=5, blank=True, null=True, default=None)
        
class Optimization(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, default=None)
    convergence = models.PositiveSmallIntegerField(default=None)
    optGasEnergy = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    optGasHomo = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    optGasLumo = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    optGasIterationNumber = models.PositiveSmallIntegerField(default=None)
        
class OptimizationGeometry(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, default=None)
    atom = models.TextField(max_length=2, blank=True, null=True, default=None)
    atomId = models.PositiveSmallIntegerField(default=None)
    input_X = models.DecimalField(blank=True, null=True, max_digits=30, decimal_places=15)
    input_Y = models.DecimalField(blank=True, null=True, max_digits=30, decimal_places=15)
    input_Z = models.DecimalField(blank=True, null=True, max_digits=30, decimal_places=15)
    final_X = models.DecimalField(blank=True, null=True, max_digits=30, decimal_places=15)
    final_Y = models.DecimalField(blank=True, null=True, max_digits=30, decimal_places=15)
    final_Z = models.DecimalField(blank=True, null=True, max_digits=30, decimal_places=15)
    
class ScfCalc(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, default=None)
    solutionEnergy = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    solutionHomo = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    solutionLumo = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    solutionIterationNumber = models.PositiveSmallIntegerField(default=None)
    gasEnergy = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    gasHomo = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    gasLumo = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    gasIterationNumber = models.PositiveSmallIntegerField(default=None)

class CpolarCalc(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, default=None)
    alpha = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    dalpha = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    beta = models.TextField(max_length=30)

class AtomicProperties(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, default=None)
    atom = models.TextField(max_length=2, blank=True, null=True, default=None)
    atomId = models.PositiveSmallIntegerField(default=None)
    nmrIsotropicshielding = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    nmrAnisotropy = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    homo_f_NN = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    homo_f_NS = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    homo_f_SN = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    homo_f_SS = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    lumo_f_NN = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    lumo_f_NS = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    lumo_f_SN = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    lumo_f_SS = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    input_X = models.DecimalField(blank=True, null=True, max_digits=30, decimal_places=15)
    input_Y = models.DecimalField(blank=True, null=True, max_digits=30, decimal_places=15)
    input_Z = models.DecimalField(blank=True, null=True, max_digits=30, decimal_places=15)
    
class ChCalc(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, default=None)
    mqmwGasDipoleMomentsX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasDipoleMomentsY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasDipoleMomentsZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasDipoleMomentsTot = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasQuadrupoleMomentsXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasQuadrupoleMomentsYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasQuadrupoleMomentsZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasQuadrupoleMomentsXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasQuadrupoleMomentsXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasQuadrupoleMomentsYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessQuadrupoleXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessQuadrupol2ZZXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessQuadrupoleXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessQuadrupoleXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessQuadrupoleYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasOctapoleMomentsXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasOctapoleMomentsYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasOctapoleMomentsZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasOctapoleMomentsXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasOctapoleMomentsXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasOctapoleMomentsXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasOctapoleMomentsXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasOctapoleMomentsYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasOctapoleMomentsYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasOctapoleMomentsXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessOctapoleXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessOctapoleYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessOctapoleZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessOctapoleXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessOctapoleXYYXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessOctapoleXXYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasTracelessOctapoleXXZYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsXXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsYYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsZZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsXXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsXXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsYYYX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsYYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsZZZX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsZZZY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsXXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsXXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsYYXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasHexadecapoleMomentsZZXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasGridpointsChargeFit = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGasPossibleMaximum = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwDipoleMomentsX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwDipoleMomentsY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwDipoleMomentsZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwDipoleMomentsTot = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwQuadrupoleMomentsXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwQuadrupoleMomentsYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwQuadrupoleMomentsZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwQuadrupoleMomentsXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwQuadrupoleMomentsXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwQuadrupoleMomentsYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessQuadrupoleXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessQuadrupol2ZZXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessQuadrupoleXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessQuadrupoleXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessQuadrupoleYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwOctapoleMomentsXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwOctapoleMomentsYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwOctapoleMomentsZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwOctapoleMomentsXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwOctapoleMomentsXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwOctapoleMomentsXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwOctapoleMomentsXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwOctapoleMomentsYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwOctapoleMomentsYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwOctapoleMomentsXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessOctapoleXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessOctapoleYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessOctapoleZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessOctapoleXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessOctapoleXYYXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessOctapoleXXYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwTracelessOctapoleXXZYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsXXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsYYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsZZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsXXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsXXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsYYYX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsYYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsZZZX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsZZZY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsXXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsXXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsYYXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwHexadecapoleMomentsZZXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwGridpointsChargeFit = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mqmwPossibleMaximum = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasDipoleMomentsX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasDipoleMomentsY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasDipoleMomentsZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasDipoleMomentsTot = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasQuadrupoleMomentsXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasQuadrupoleMomentsYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasQuadrupoleMomentsZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasQuadrupoleMomentsXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasQuadrupoleMomentsXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasQuadrupoleMomentsYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessQuadrupoleXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessQuadrupol2ZZXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessQuadrupoleXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessQuadrupoleXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessQuadrupoleYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasOctapoleMomentsXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasOctapoleMomentsYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasOctapoleMomentsZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasOctapoleMomentsXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasOctapoleMomentsXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasOctapoleMomentsXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasOctapoleMomentsXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasOctapoleMomentsYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasOctapoleMomentsYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasOctapoleMomentsXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessOctapoleXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessOctapoleYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessOctapoleZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessOctapoleXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessOctapoleXYYXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessOctapoleXXYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasTracelessOctapoleXXZYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsXXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsYYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsZZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsXXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsXXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsYYYX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsYYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsZZZX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsZZZY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsXXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsXXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsYYXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcGasHexadecapoleMomentsZZXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcDipoleMomentsX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcDipoleMomentsY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcDipoleMomentsZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcDipoleMomentsTot = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcQuadrupoleMomentsXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcQuadrupoleMomentsYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcQuadrupoleMomentsZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcQuadrupoleMomentsXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcQuadrupoleMomentsXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcQuadrupoleMomentsYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessQuadrupoleXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessQuadrupol2ZZXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessQuadrupoleXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessQuadrupoleXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessQuadrupoleYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcOctapoleMomentsXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcOctapoleMomentsYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcOctapoleMomentsZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcOctapoleMomentsXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcOctapoleMomentsXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcOctapoleMomentsXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcOctapoleMomentsXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcOctapoleMomentsYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcOctapoleMomentsYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcOctapoleMomentsXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessOctapoleXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessOctapoleYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessOctapoleZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessOctapoleXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessOctapoleXYYXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessOctapoleXXYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcTracelessOctapoleXXZYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsXXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsYYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsZZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsXXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsXXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsYYYX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsYYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsZZZX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsZZZY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsXXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsXXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsYYXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mepcHexadecapoleMomentsZZXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasDipoleMomentsX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasDipoleMomentsY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasDipoleMomentsZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasDipoleMomentsTot = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasQuadrupoleMomentsXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasQuadrupoleMomentsYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasQuadrupoleMomentsZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasQuadrupoleMomentsXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasQuadrupoleMomentsXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasQuadrupoleMomentsYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessQuadrupoleXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessQuadrupol2ZZXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessQuadrupoleXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessQuadrupoleXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessQuadrupoleYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasOctapoleMomentsXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasOctapoleMomentsYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasOctapoleMomentsZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasOctapoleMomentsXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasOctapoleMomentsXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasOctapoleMomentsXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasOctapoleMomentsXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasOctapoleMomentsYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasOctapoleMomentsYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasOctapoleMomentsXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessOctapoleXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessOctapoleYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessOctapoleZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessOctapoleXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessOctapoleXYYXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessOctapoleXXYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasTracelessOctapoleXXZYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsXXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsYYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsZZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsXXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsXXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsYYYX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsYYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsZZZX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsZZZY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsXXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsXXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsYYXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcGasHexadecapoleMomentsZZXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcDipoleMomentsX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcDipoleMomentsY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcDipoleMomentsZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcDipoleMomentsTot = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcQuadrupoleMomentsXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcQuadrupoleMomentsYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcQuadrupoleMomentsZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcQuadrupoleMomentsXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcQuadrupoleMomentsXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcQuadrupoleMomentsYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessQuadrupoleXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessQuadrupol2ZZXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessQuadrupoleXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessQuadrupoleXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessQuadrupoleYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcOctapoleMomentsXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcOctapoleMomentsYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcOctapoleMomentsZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcOctapoleMomentsXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcOctapoleMomentsXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcOctapoleMomentsXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcOctapoleMomentsXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcOctapoleMomentsYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcOctapoleMomentsYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcOctapoleMomentsXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessOctapoleXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessOctapoleYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessOctapoleZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessOctapoleXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessOctapoleXYYXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessOctapoleXXYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcTracelessOctapoleXXZYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsXXXX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsYYYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsZZZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsXXXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsXXXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsYYYX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsYYYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsZZZX = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsZZZY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsXXYY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsXXZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsYYZZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsXXYZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsYYXZ = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    mmcHexadecapoleMomentsZZXY = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)


class PairMatchSmilesPackage(models.Model):
    user = models.ForeignKey(User, null=True, editable=False, on_delete=models.SET_NULL) 
    package = models.FileField(upload_to='{}'.format('pairdatapackages')) 
    packageDate=models.DateTimeField(auto_now=True)
    notes = models.TextField(max_length=500)
    
class Reaction(models.Model):
    reactant = models.ForeignKey(Molecule, null=True, editable=False, on_delete=models.SET_NULL, related_name='reactant')
    product = models.ForeignKey(Molecule, null=True, editable=False, on_delete=models.SET_NULL, related_name='product')
    bondType = models.TextField(max_length=10)
    reactionEnergy = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    reactantEnergy = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    productEnergy = models.DecimalField(blank=True, null=True, max_digits=10, decimal_places=5)
    pairPackage = models.ForeignKey(PairMatchSmilesPackage, null=True, editable=False, on_delete=models.SET_NULL)
    
    

    
    

    
    
    
    
    
    
    
