# Generated by Django 2.1 on 2021-02-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atomicproperties',
            old_name='jobId',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='chcalc',
            old_name='jobId',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='cpolarcalc',
            old_name='jobId',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='optimization',
            old_name='jobId',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='optimizationgeometry',
            old_name='jobId',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='otherinfo',
            old_name='jobId',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='pbfcalc',
            old_name='jobId',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='scfcalc',
            old_name='jobId',
            new_name='job',
        ),
    ]
